<a href="https://colab.research.google.com/github/niginadavronova/collab.works/blob/main/10_MA%CA%BCLUMOTLARGA_ISHLOV_BERISH_10_11_HTML_JSON_API_o%CA%BBqish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**
#10.11. Veb sahifalardan oʻqish. JSON va API
**Bu vazifalarni bajargach, veb sahifalardan maʼlumot olish, JSON bilan ishlash va API soʻrovlarini yuborish koʻnikmalarini egallaysiz.**

#1-topshiriq
1. Pandas kutubxonasidan foydalanib, quyida berilgan link ichidan barcha jadvallarni o‘qing va roʻyxat shaklida saqlang.

Link 403 Forbidden (Manzil to'g'ri, lekin kirish taqiqlangan.) xatoligini bermasligi uchun, sahifani avval requests bilan yuklab, keyin pd.read_html() ga HTML matnini bering.

 * https://en.wikipedia.org/wiki/Fossil_fuel_exporters
2. Har bir jadvalning birinchi 1 qatorini ekranga chiqaring.

In [4]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/Fossil_fuel_exporters"
headers = {'User-Agent': 'Mozilla/5.0'}

response = requests.get(url, headers=headers)

fuel = pd.read_html(response.text)
fuel[0].head(1)

/tmp/ipykernel_4869/385952395.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  fuel = pd.read_html(response.text)

    0                                                  1
0 NaN  This article needs to be updated. Please help ...

#2-topshiriq
Yuqorida yaratilgan jadvallar roʻyxatidan eng uzunini `largest_data.csv` fayliga saqlang.

In [5]:
largest_df = max(fuel, key=len)

largest_df.to_csv("largest_data.csv", index=False)

print("Eng uzun jadval muvaffaqiyatli saqlandi!")

Eng uzun jadval muvaffaqiyatli saqlandi!

#3-topshiriq
1. Quyidagi link orqali json maʼlumotni yuklab oling va uni climate_change_co2.json nomi bilan saqlang.
 * https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/json_data.json
2. Maʼlumotlar boshidan 5 ta qatorni ekranga chiqaring!

In [6]:
url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/json_data.json"
response = requests.get(url)

with open("climate_change_co2.json", "w", encoding="utf-8") as f:
    f.write(response.text)

df = pd.read_json("climate_change_co2.json")

df.head(5)

,Year,Total,Gas Fuel,Liquid Fuel,Solid Fuel,Cement,Gas Flaring,Per Capita
0,2010,9167,1702,3114,3842,450,59,1.33
1,2009,8740,1585,3056,3620,413,66,1.28
2,2008,8783,1631,3122,3571,388,71,1.30
3,2007,8566,1572,3081,3464,382,68,1.28
4,2006,8370,1525,3089,3339,356,61,1.27

#4-topshiriq
1. Quyida berilgan linkga `get` soʻrovini yuborish orqali `json` maʼlumotlarini `posts.json` fayliga saqlang.
  * https://jsonplaceholder.typicode.com/posts/
2. Ushbu maʼlumotlarni dataframe koʻrinishida saqlang va tasodifiy 5 ta qatorni ekranga chiqaring.

In [7]:
url = "https://jsonplaceholder.typicode.com/posts/"
response = requests.get(url)

with open("posts.json", "w", encoding="utf-8") as f:
    f.write(response.text)

df = pd.read_json("posts.json")

df.sample(5)

,userId,id,title,body
72,8,73,consequuntur deleniti eos quia temporibus ab a...,voluptatem cumque tenetur consequatur expedita...
93,10,94,qui qui voluptates illo iste minima,aspernatur expedita soluta quo ab ut similique...
18,2,19,adipisci placeat illum aut reiciendis qui,illum quis cupiditate provident sit magnam\nea...
94,10,95,id minus libero illum nam ad officiis,earum voluptatem facere provident blanditiis v...
40,5,41,non est facere,molestias id nostrum\nexcepturi molestiae dolo...