<a href="https://colab.research.google.com/github/niginadavronova/collab.works/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%2210_MA%CA%BCLUMOTLARGA_ISHLOV_BERISH_10_5_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**
#10.5. Fayldan oʻqish va unga yozish. HDF5
**Bu vazifalarni bajargach, CSV, Excel va HDF5 formatlarida fayllarni oʻqish hamda saqlash, yaʼni data processing (ma’lumotlarga ishlov berish) koʻnikmasini oʻzlashtirasiz.**


#1-topshiriq


1.    Quyidagi link orqali maʼlumotlarni Pandas dataframeʼiga yuklab oling.
    
  *   https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv



2.   Yuklab olingan maʼlumotlarni `aqi.csv` fayliga saqlang.

3. Saqlab olingan `aqi.csv` faylining oxirgi 5 ta qatorini oʻqing.

Eslatma: fayl nomini `aqi.csv` deb saqlaganimizning sababi AQI – Air Quality Index, yaʼni havo sifati indeksi deganidir. Bizning maʼlumotlarimizda davlatlarning havo sifati haqidagi maʼlumotlar saqlangan!

In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv")
df.to_csv("aqi.csv", index=False)
df.tail()

             Date                   Country    Status  AQI Value
18116  2025-03-06  United States of America  Moderate         82
18117  2025-03-06                Uzbekistan      Good         17
18118  2025-03-06                   Vatican  Moderate         65
18119  2025-03-06                 Venezuela      Good         11
18120  2025-03-06                   Vietnam  Moderate         64

#2-topshiriq
1. Saqlab olingan `aqi.csv` faylidagi maʼlumotlarning faqat 2024-yilga tegishlisini excel faylga `aqi_2024.xlsx` koʻrinishida saqlab oling.
2. Saqlab olingan `aqi_2024.xlsx` faylidan Oʻzbekistonga tegishli maʼlumotni (qatorlarni) oʻqing.

In [2]:
#javobni shu yerda yozing.
df=pd.read_csv("aqi.csv")
df_2024=df[df["Date"].str.startswith("2024")]
df_2024.to_excel("aqi_2024.xlsx", index=False)

aqi_excel=pd.read_excel("aqi_2024.xlsx")
uzb_2024=aqi_excel[aqi_excel["Country"]=="Uzbekistan"]
uzb_2024

            Date     Country     Status  AQI Value
128   2024-06-06  Uzbekistan       Good         21
261   2024-06-06  Uzbekistan       Good         21
394   2024-06-13  Uzbekistan       Good         35
525   2024-06-20  Uzbekistan       Good         10
656   2024-06-27  Uzbekistan       Good         26
786   2024-07-04  Uzbekistan       Good         19
914   2024-07-11  Uzbekistan       Good         26
1043  2024-07-18  Uzbekistan       Good         42
1173  2024-07-25  Uzbekistan       Good         30
1302  2024-08-01  Uzbekistan       Good         45
1432  2024-08-08  Uzbekistan       Good         42
1562  2024-08-15  Uzbekistan       Good         26
1691  2024-08-22  Uzbekistan       Good         23
1819  2024-08-29  Uzbekistan   Moderate         56
1948  2024-09-05  Uzbekistan   Moderate         70
2075  2024-09-12  Uzbekistan       Good         45
2204  2024-09-19  Uzbekistan  Hazardous        500
2331  2024-09-26  Uzbekistan  Unhealthy        157
2450  2024-10-03  Uzbekistan       Good         34
2578  2024-10-10  Uzbekistan   Moderate         63
2700  2024-10-17  Uzbekistan  Unhealthy        195
2821  2024-10-24  Uzbekistan  Unhealthy        180
2941  2024-10-31  Uzbekistan  Unhealthy        153
3060  2024-11-07  Uzbekistan   Moderate         65
3179  2024-11-14  Uzbekistan  Unhealthy        151
3297  2024-11-21  Uzbekistan  Unhealthy        152
3419  2024-11-28  Uzbekistan       Good         38
3541  2024-12-05  Uzbekistan   Moderate         83
3663  2024-12-12  Uzbekistan   Moderate        100
3786  2024-12-19  Uzbekistan       Good         34
3907  2024-12-26  Uzbekistan   Moderate         98

#3-topshiriq
1. `aqi.csv` faylidagi maʼlumotlarni oʻrganib chiqsangiz, bu faylda 2022–2025-yillar oraligʻidagi havo sifati haqidagi maʼlumotlarni koʻrishingiz mumkin. Hozir sizga vazifa:
  * `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllariga `aqi.csv` faylidagi maʼlumotlarning mos davrlarini saqlang. Misol uchun, `aqi_2022` fayli 2022-yildagi havo sifati haqidagi maʼlumotlarni oʻzida saqlaydi.

In [3]:
#javobni shu yerda yozing.
df=pd.read_csv("aqi.csv")
df_2022=df[df["Date"].str.startswith("2022")].to_csv("aqi_2022.csv", index=False)
df_2023=df[df["Date"].str.startswith("2023")].to_csv("aqi_2023.csv", index=False)
df_2024=df[df["Date"].str.startswith("2024")].to_csv("aqi_2024.csv", index=False)
df_2025=df[df["Date"].str.startswith("2025")].to_csv("aqi_2025.csv", index=False)

#4-topshiriq
1. Saqlab olingan `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllarini HDF5 formatida saqlang. Fayl nomini `aqi.h5` deb nomlang. Kalit (key) sifatida fayllarning yillarini bering. Misol uchun, key=2025.

In [4]:
hdfdate = pd.HDFStore("aqi.h5")

hdfdate.put("2022", pd.read_csv("aqi_2022.csv"))
hdfdate.put("2023", pd.read_csv("aqi_2023.csv"))
hdfdate.put("2024", pd.read_csv("aqi_2024.csv"))
hdfdate.put("2025", pd.read_csv("aqi_2025.csv"))

hdfdate.close()

/usr/local/lib/python3.13/dist-packages/tables/path.py:146: NaturalNameWarning: object name is not a valid Python identifier: '2022'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.13/dist-packages/tables/path.py:146: NaturalNameWarning: object name is not a valid Python identifier: '2023'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.13/dist-packages/tables/path.py:146: NaturalNameWarning: object name is not a valid Python identifier: '2024'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/usr/local/lib/python3.13/dist-packages/tables/path.py:146: NaturalNameWarning: object name is not a valid Python identifier: '2025'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

#5-topshiriq
1. `aqi.h5` faylidan maʼlumotlarni oʻqing va 2025-yilga tegishli maʼlumotlarni yangi dataframeʼga saqlang.
2. `aqi.h5` faylida 2025-yilning qaysi oylari uchun maʼlumotlar bor? Shu oylar roʻyxatini ekranga chiqaring!

In [12]:
dfr_2025=pd.read_hdf("aqi.h5", key="2025")
oylar=dfr_2025["Date"].unique()
oylar

array(['2025-01-02', '2025-01-09', '2025-01-16', '2025-01-23',
       '2025-01-30', '2025-02-06', '2025-02-13', '2025-02-20',
       '2025-02-27', '2025-03-06'], dtype=object)

Vazifa: aqi.h5 faylidan istalgan yil (masalan, 2024) ma'lumotlarini o'qib oling va oylar bo'yicha havo sifati (AQI Value) ko'rsatkichining o'rtacha qiymatini (mean) hisoblang.

In [10]:
df_24=pd.read_hdf("aqi.h5", key="2024")
orta=df_24["AQI Value"].mean()
orta

np.float64(64.23395551009972)

Qiymatlar bo'yicha saralash (sort_values)
Vazifa: 2025-yilga tegishli ma'lumotlarda havo sifati (AQI Value) eng yomon (eng yuqori) bo'lgan kunlarni aniqlash uchun jadvalni AQI Value bo'yicha kamayish tartibida (ascending=False) saralang va eng yuqori 5 ta qatorni chiqaring.

In [17]:
df_25=pd.read_hdf("aqi.h5", key="2025")
bad_day=df_25.sort_values(by="AQI Value", ascending=False)
bad_day.head()

           Date     Country     Status  AQI Value
500  2025-01-30  Bangladesh  Hazardous        532
538  2025-01-30       India  Hazardous        502
623  2025-02-06  Bangladesh  Hazardous        411
388  2025-01-23        Chad  Hazardous        410
115  2025-01-02      Uganda  Hazardous        306